### ISSUE TITLE
PDF Failing to Open on 20.0.0 Beta2 (and on Beta1)

### ISSUE THREAD

**Issue by scottalanmiller** [nextcloud/files_pdfviewer#208] opened 2020-08-28 19:36 UTC
### Steps to reproduce
1. Update to 20 Beta series
2. Try to open a PDF

### Expected behaviour
That the PDF will open in the browser

### Actual behaviour
A PDF reader opens, nothing else happens.

### Server configuration
Can't use the issue tool, it doesn't work in the beta.

**Operating system**:
Fedora 32

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
12.0.0 Beta 2

**Where did you install Nextcloud from:**
Years ago. Manual install from NC site.

**List of activated apps:**

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - admin_audit: 1.10.0
  - audioplayer: 2.11.2
  - breezedark: 19.0.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.0
  - duplicatefinder: 0.0.2
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - files_antivirus: 2.4.1
  - files_downloadactivity: 1.8.0
  - files_pdfviewer: 2.0.O
  - files_retention: 1.8.2
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_texteditor: 2.11.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - issuetemplate: 0.6.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 3.6.4
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.3
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - side_menu: 1.8.5
  - spreed: 10.0.0-beta.1
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.3
  - text: 3.1.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 0.0.2
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - bruteforcesettings
  - dashboard
  - encryption
  - federation
  - files_external
  - support
  - theming
  - user_ldap

**Nextcloud configuration:**

PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "20.0.0.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "beta",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "files_downloadactivity",
            "audioplayer",
            "tasks",
            "spreed",
            "ransomware_protection",
            "files_retention",
            "richdocuments",
            "bruteforcesettings",
            "breezedark",
            "drawio",
            "files_texteditor",
            "printer",
            "issuetemplate",
            "impersonate"
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

### Client configuration
**Browser:**
Firefox and Chrome

**Operating system:**
Ubuntu 20.04 and Windows 10

**Comment by skjnldsv** [comment] 2020-08-29 07:24
Hey!
Thanks a lot! :)
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by scottalanmiller** [comment] 2020-08-29 23:04
Sorry, took all day to get this. Tested as many things as I could, finally got this error in the brower console (Chrome)

Opening viewer for file  /NTG/New Hires/Welcome to NTG from Business Infrastructure Support.pdf
Viewer.vue:452 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at s.updateTitle (Viewer.vue:452)
    at Viewer.vue:333
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at oe (viewer-main.js?v=1a065535:394)
    at s (viewer-main.js?v=1a065535:394)
    at viewer-main.js?v=1a065535:394
    at new Promise (<anonymous>)
    at viewer-main.js?v=1a065535:394

**Comment by Dragon988** [comment] 2020-08-30 22:37
I can confirm that on 20 beta 2 PDF's do not open (viewer does, pdf does not load) on firefox 80 on Linux.

**Comment by Dragon988** [comment] 2020-08-30 22:39
There is no error when opening the pdf. It's only when closing the viewer.

sendRemoveListener on closed conduit CanvasBlocker@kkapsner.de.2473901163163 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:1275
    removeListener resource://gre/modules/ExtensionChild.jsm:663
    removeListener resource://gre/modules/ExtensionChild.jsm:886
    onChanged chrome://extensions/content/child/ext-storage.js:337
    removeListener resource://gre/modules/ExtensionCommon.jsm:2517
    revoke resource://gre/modules/ExtensionCommon.jsm:2539
    close resource://gre/modules/ExtensionCommon.jsm:2544
    unload resource://gre/modules/ExtensionCommon.jsm:909
    close resource://gre/modules/ExtensionContent.jsm:927
    destroyed resource://gre/modules/ExtensionContent.jsm:1005
    observe resource://gre/modules/ExtensionContent.jsm:1023

**Comment by Dragon988** [comment] 2020-08-30 22:39
Also, disabling the canvas blocker addon results in the same problem, only no error listed in console.

**Comment by Dragon988** [comment] 2020-08-30 22:43
Same issue on android with firefox.

**Comment by scottalanmiller** [comment] 2020-08-30 22:50
Yeah, same here. No blockers, and no errors.  Happens with photos and other files now too I realize. So not PDF specific.

**Comment by Dragon988** [comment] 2020-08-30 22:55
> Yeah, same here. No blockers, and no errors. Happens with photos and other files now too I realize. So not PDF specific.

It's PDF specific for me. Photos work.

**Comment by skjnldsv** [comment] 2020-08-31 08:11
We're talking about everywhere or just public pages?

**Comment by Dragon988** [comment] 2020-08-31 19:46
> We're talking about everywhere or just public pages?

Yes, everywhere.

**Comment by Dragon988** [comment] 2020-08-31 21:43
I'll go ahead and try getting images or a video this evening for you @skjnldsv but it's basically a blank viewer without the pdf loading at all.

Downloading the PDF from nextcloud and opening on my OS pdf viewer works, so the file is there and accessible.

There are no errors for me in the web browser console. nextcloud.log does have some JS related errors but it doesn't appear to be related to this issue. They don't appear when opening the pdf viewer.

**Comment by scottalanmiller** [comment] 2020-08-31 21:49
Exactly, it brings up the views, and just nothing happens. It just sits there. Files that worked fine before the update.

**Comment by scottalanmiller** [comment] 2020-08-31 21:52
![pdf_loading](https://user-images.githubusercontent.com/279397/91772306-3f77b980-ebaa-11ea-9699-76df4ff85bd5.gif)

I attached a GIF of the loading issue. No errors in the browser, it just sits like this forever.

**Comment by Dragon988** [comment] 2020-08-31 21:53
> ![pdf_loading](https://user-images.githubusercontent.com/279397/91772306-3f77b980-ebaa-11ea-9699-76df4ff85bd5.gif)
> 
> I attached a GIF of the loading issue. No errors in the browser, it just sits like this forever.

That's not what I see. I see the viewer actually load on the screen, entire thing. It just doesn't show the PDF.

Looks like there are two separate issues here.

**Comment by scottalanmiller** [comment] 2020-08-31 21:55
> > I attached a GIF of the loading issue. No errors in the browser, it just sits like this forever.
> 
> That's not what I see. I see the viewer actually load on the screen, entire thing. It just doesn't show the PDF.
> 
> Looks like there are two separate issues here.

You know now that you mention it, I used to see that too. But that stopped at some point and now it only does this.

**Comment by Dragon988** [comment] 2020-08-31 21:56
> > > I attached a GIF of the loading issue. No errors in the browser, it just sits like this forever.
> > 
> > 
> > That's not what I see. I see the viewer actually load on the screen, entire thing. It just doesn't show the PDF.
> > Looks like there are two separate issues here.
> 
> You know now that you mention it, I used to see that too. But that stopped at some point and now it only does this.

Which is funny because when I originally installed 20 beta 2 nothing opened for me at all even images. But hard refreshing the website several times fixed that.

Hmmm.

**Comment by Dragon988** [comment] 2020-08-31 22:00
Might be a redis or nginx cache issue. I'll do some tests when I have time and post an update on this issue.

**Comment by skjnldsv** [comment] 2020-09-01 04:35
Are  you testing beta2 from git or from the official beta releases?

**Comment by Dragon988** [comment] 2020-09-01 05:31
> Are you testing beta2 from git or from the official beta releases?

Official release.

**Comment by Dragon988** [comment] 2020-09-01 05:32
https://download.nextcloud.com/server/prereleases/nextcloud-20.0.0beta2.zip

**Comment by Dragon988** [comment] 2020-09-01 05:37
Fresh install, did not upgrade. Using PHP 7.4 with postgresql.

**Comment by skjnldsv** [comment] 2020-09-01 07:23
Thanks, found bug. fix in #209

**Closed** 2020-09-01 07:33 UTC
Labels: 20-feedback, 3. to review, bug
