### ISSUE TITLE
Quick double-click on PDF files opens PDF preview 2 times and cannot be closed afterwards via the X in the upper right corner

### ISSUE THREAD

**Issue by fbroen** [nextcloud/files_pdfviewer#338] opened 2021-03-15 13:22 UTC
### Steps to reproduce
1. Quick double-click on a PDF file
2. The PDF-Preview opens (in background you can see the black window opens 2 times
3. Click the white close X in the upper right corner from the black preview window

### Expected behaviour
The PDF incl. black background should close and the files should become visible again

### Actual behaviour
The PDF close, but the black background stays in foreground without any controls. You have to relaod the page, to show the files again.

### Server configuration

Operating system: CentOS Linux 7.9.2009 (Core)

Web server: Plesk Obsidian, Version 18.0.34 with Apache & Nginx

Database: MariaDB 10.3.28

PHP version: 7.4.16

Nextcloud version: 21.0.0.18

Where did you install Nextcloud from: https://download.nextcloud.com/server/installer/setup-nextcloud.php

List of activated apps:

Accessibility	1.7.0	Vorgestellt	
Activities for shared file downloads, visible to all admins	1.10.0		
Activity	2.14.3	Vorgestellt	
Auditing / Logging	1.11.0	Vorgestellt	
File sharing	1.13.1	Vorgestellt	
Log Reader	2.6.0	Vorgestellt	
Monitoring	1.11.0	Vorgestellt	
Nextcloud announcements	1.10.0	Vorgestellt	
Notifications	2.9.0	Vorgestellt	
Password policy	1.11.0	Vorgestellt	
PDF viewer	2.1.0	Vorgestellt	
Privacy	1.5.0	Vorgestellt	
Right click	1.0.0	Vorgestellt	
Theming	1.12.0	Vorgestellt	
Update notification	1.11.0	Vorgestellt	
Video player	1.10.0	Vorgestellt

```

Nextcloud configuration:

$CONFIG = array (
  'activity_expire_days' => 365,
  'default_language' => 'de',
  'default_locale' => 'de_DE',
  'default_phone_region' => 'DE',
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'datadirectory' => '/var/www/vhosts/xxx/xxx',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '21.0.0.18',
  'overwrite.cli.url' => 'xxx',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
);

```

### Client configuration
Browser: Google Chrome Version 89.0.4389.82 (Offizieller Build) (64-Bit)

Operating system: Windows 10 20H2

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here: private
```

#### Browser log
```
Insert your browser log here, this could for example include:

The javascript console log:
Uncaught TypeError: Cannot read property 'contains' of undefined
    at a.hasNodeOrAnyParentClass (excludeClickOutsideClasses.js:22)
    at a.clickOutsideMiddleware (excludeClickOutsideClasses.js:22)
    at r (v-click-outside.umd.js:1)
    at v-click-outside.umd.js:1
app.js:1281 PDF f62556208f49a970e51d88e142193c99 [1.4 GPL Ghostscript 9.52 / PDFCreator Free 4.1.2] (PDF.js: 2.5.207)

```

**Comment by kesselb** [comment] 2021-03-18 13:54
I can reproduce it on 21 but not with master.

**Comment by szaimen** [comment] 2021-07-17 19:29
I think this is a duplicate of https://github.com/nextcloud/viewer/issues/893

**Closed by szaimen** 2021-07-17 19:29 UTC
Labels: 1. to develop, bug
