### ISSUE TITLE
Blank PDF view with error

### ISSUE THREAD

**Issue by ChrisPeri** [nextcloud/files_pdfviewer#770] opened 2023-07-09 11:49 UTC
I have uploaded several PDF files. non of them can open in web pdf view.
Instead, i get a blank page with the below error message:
"Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security."

**Console error:**
GET https://_webpage_.com/index.php/apps/files_pdfviewer/?file=_filename_.pdf&canDownload=1 406

My solution is builded on shared HostGator.

**Comment by szaimen** [comment] 2023-07-10 14:22
Hi, can you check if disabling mod_security makes it work? If yes is this a configuration issue and not a bug of the files_pdfviewer.

**Comment by ChrisPeri** [comment] 2023-07-10 14:51
/config/.htaccess -> mod_security:
<IfModule mod_security.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
</IfModule>

**Comment by szaimen** [comment] 2023-07-10 14:59
So mod_security is disabled and now it works?

**Comment by szaimen** [comment] 2023-07-11 15:37
But why is this error printed then?

> This error was generated by Mod_Security."

**Comment by ChrisPeri** [comment] 2023-07-11 15:42
i don't know.

Please verify that the file that contain mod_security is the below. Also, i have added the content of the file.

Path: /config/.htaccess 

Content: 
# Section for Apache 2.4 to 2.6
<IfModule mod_authz_core.c>
  Require all denied
</IfModule>
<IfModule mod_access_compat.c>
  Order Allow,Deny
  Deny from all
  Satisfy All
</IfModule>

# Section for Apache 2.2
<IfModule !mod_authz_core.c>
  <IfModule !mod_access_compat.c>
    <IfModule mod_authz_host.c>
      Order Allow,Deny
      Deny from all
    </IfModule>
    Satisfy All
  </IfModule>
</IfModule>

# Section for Apache 2.2 to 2.6
<IfModule mod_autoindex.c>
  IndexIgnore *
</IfModule>

<IfModule mod_security.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
</IfModule>

**Comment by joshtrichards** [comment] 2024-05-05 13:39
This is still coming from mod_security. Perhaps the ability to disable mod_security via htaccess is not itself enabled?

In any case, it's not a bug in our app. Closing.

**Closed by joshtrichards** 2024-05-05 13:39 UTC
Labels: needs info
