### ISSUE TITLE
PDF Viewer doesn't open files correctly at fresh Nextcloud

### ISSUE THREAD

**Issue by vvl-rulez** [nextcloud/files_pdfviewer#108] opened 2018-11-15 11:45 UTC
### Steps to reproduce
1. Install clear Nextcloud 14.0.3
2. Try to open Nextcloud Manual.pdf

### Expected behaviour
PDF should be opened in PDF Viewer app correctly

### Actual behaviour
![screenshot_20181115_144335](https://user-images.githubusercontent.com/13856385/48550862-e6f7ff00-e8e4-11e8-979e-cf1e131a71fc.png)

### Server configuration

**Operating system**:
Archlinux
**Web server:**
nginx
**Database:**
MariaDB 10.4
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Where did you install Nextcloud from:**
Archlinux repository

**List of activated apps:**

<details>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.3
  - checksum: 0.4.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.5.0
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_nextcloud_notification: 0.2.4
  - twofactor_totp: 1.5.0
  - twofactor_u2f: 1.6.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
```

</details>

**Nextcloud configuration:**

<details> 

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mynextcloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/mynextcloud",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "filesystem_check_changes": 0,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log_type": "syslog",
        "syslog_tag": "nextcloud",
        "logfile": "",
        "loglevel": "3",
        "theme": "",
        "updater.release.channel": "stable",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
``` 

</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**
Archlinux, Windows 10
### Logs
Clear (no errors)
#### Nextcloud log (data/owncloud.log)
```
Clear (no errors)
```

#### Browser log
Unexpected server response
PDF.js v1.9.426 (build: 2558a58d)
Message: Unexpected server response (0) while retrieving PDF "https://mynextcloud/remote.php/webdav/Nextcloud Manual.pdf".
```

**Comment by skjnldsv** [comment] 2020-08-19 12:35
Looks like a server issue.
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-19 12:35 UTC
Labels: 0. Needs triage, bug
