### ISSUE TITLE
"Missing PDF file" errors after NextCloud upgrade 21.0.1 -> 21.0.2

### ISSUE THREAD

**Issue by Infogeekx** [nextcloud/files_pdfviewer#383] opened 2021-05-20 23:50 UTC
PDF.js v2.5.207 (build: 0974d6052)

**Comment by hobbsecky** [comment] 2021-05-21 01:52
Same here.

**Comment by Synochy** [comment] 2021-05-21 09:27
Same problem here migrating from Nextcloud 21.0.1 to 21.0.2

**Comment by thom7e** [comment] 2021-05-21 14:29
Same Problem here after migrating to 21.0.2

**Comment by beardhatcode** [comment] 2021-05-21 18:58
Duplicate of #381

**Closed by beardhatcode** 2021-05-21 18:58 UTC
