### ISSUE TITLE
Some PDF only loading first/second page

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/files_pdfviewer#123] opened 2019-03-18 07:48 UTC
## Steps to reproduce
(Only sometimes on some documents)
1. Open a PDF file
2. Scroll

### Expected behaviour
Document should be displayed

### Actual behaviour
First / second page is displayed... every page after that is white.

Workaround: Reloading the page helps sometimes...

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache
 
**Database:** MariaDB

**PHP version:** PHP 7.2

**Nextcloud version:** 15.0.5

**Where did you install Nextcloud from:** Source / Web

### Client configuration
**Browser:** Chrome (Desktop & Mobile)

**Comment by GovetaXV** [comment] 2019-05-31 17:16
same problem.

**Comment by skjnldsv** [comment] 2020-08-19 12:32
Please provide sample pdf

As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-19 12:32 UTC
