### ISSUE TITLE
No way to close the pdf viewer on mobile/in portrait mode

### ISSUE THREAD

**Issue by szaimen** [nextcloud/files_pdfviewer#279] opened 2020-12-30 14:02 UTC
### Steps to reproduce
1. install NC20
2. open a pdf file with the pdf viewer on mobile or laptop/pc in portrait mode
3. wait a few seconds until the viewer buttons disappear (that lay ontop of the pdf viewer for a short time)
4. see screenshots

### Expected behaviour
should be able to close the pdf viewer

### Actual behaviour
cannot close the pdf viewer

### Screenshots
![image](https://user-images.githubusercontent.com/42591237/103355813-879ede00-4aaf-11eb-977d-643e691bbdcf.png)
![image](https://user-images.githubusercontent.com/42591237/103355982-fc721800-4aaf-11eb-8bb8-2788e905b5b3.png)

**Comment by skjnldsv** [comment] 2021-01-04 10:24
We need to add a way for viewer types to register if they want the clear-view feature enabled or not.

**Comment by oogie** [comment] 2021-01-14 18:00
+1: I also have this problem, would be awesome if fixed!

### Effected devices / browsers
Encountered this unwanted behaviour on Android 11 (Chrome 87.0 & FF 84.1), IOS 14.3 (Safari) and Windows 10 with small browser window sizes (FF 84.0 & Chrome 87.0). I run Nextcloud version 20.0.4 and PDF viewer 2.0.1 (according to the Nextcloud Apps overview)

### Possible correct behaviour
Some sort of close button would obviously be nice. In addition: closing the whole PDF modal when the browser's back button is pressed (via window.onpopstate) would, in my opinion, be very intuitive.

**Comment by komdrive** [comment] 2021-03-11 09:50
+1, and I also see this problem, really looking forward to the fix.
Android 11, Chrome 89, Nextcloud 20.0.8.1 (PDF Viewer 2.0.1)

I get out of the situation: press "refresh page" and press "cancel" or press "back" and "refresh"

**Comment by elpraga** [comment] 2021-03-30 21:00
I am also experiencing this issue. Would it be possible to get the Close menu option back?

I am aware that it was deliberately eliminated from the menu, but in my opinion, it would be better to have two options in all cases to close the viewer rather than none in some cases.

**Comment by elpraga** [comment] 2021-03-30 21:23
Displaying linear (web optimised) PDFs can be enabled on Chrome using this extension https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm (which in turn uses pdf.js)

**Comment by szaimen** [comment] 2021-04-12 15:27
As I said in https://github.com/nextcloud/viewer/issues/848#issuecomment-815976408:

> Maybe a fix would be to not hide the buttons at all? Would also solve the detectability issue on mobile devices...

**Comment by szaimen** [comment] 2021-04-12 15:48
@skjnldsv is this something that must get fixed in the viewer repository or here? Do you have some pointers?

**Comment by skjnldsv** [comment] 2021-04-13 05:27
We need to add an option in the way apps register viewer rendering modules to disable the fade-out of the menus. So should be in viewer AND then here.

**Comment by skjnldsv** [comment] 2021-04-13 05:31
https://github.com/nextcloud/viewer/blob/b3eb0913bff415f3ca30661b997ba27fa3ea6373/src/views/Viewer.vue#L29
https://github.com/nextcloud/viewer/blob/b3eb0913bff415f3ca30661b997ba27fa3ea6373/src/services/Viewer.js#L68

Add an `options` in models: https://github.com/nextcloud/viewer/blob/b3eb0913bff415f3ca30661b997ba27fa3ea6373/src/models/videos.js#L25-L41
https://github.com/nextcloud/files_pdfviewer/blob/92eec1d5d2b1ab0739be370fb95921ea9fb79aef/src/main.js#L26-L35

And use the handler `options.clearViewDelay` if any :thinking:

**Closed** 2021-07-13 12:29 UTC
Labels: 1. to develop, bug

**Comment by elpraga** [comment] 2021-07-13 12:39
When can this change be expected to land in the updates?

**Comment by szaimen** [comment] 2021-07-13 12:41
In the next minor updates

**Comment by elpraga** [comment] 2021-07-13 12:49
Thank you for your swift answer!

**Comment by CircuitC** [comment] 2021-07-28 23:00
The issue is closed but I still have this issue in the iOS app and in Safari mobile.

**Comment by szaimen** [comment] 2021-07-29 18:43
It will be fixed with the next releases
