### ISSUE TITLE
Char "-" not showing!

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/files_pdfviewer#102] opened 2018-10-03 11:38 UTC
### Steps to reproduce
1. Upload PDF
2. Open PDF
3. Char "-" showing as Space

### Expected behaviour
Open PDF and show correct chars.

### Actual behaviour

![unbenannt](https://user-images.githubusercontent.com/33482537/46408178-8a17ff00-c711-11e8-99d6-47d2e7fa6efd.png)

**Operating system**: Ubuntu 16.0.5 LTS

**Web server:** newest apt

**Database:** newest apt

**PHP version:** newest apt

**Nextcloud version:** 13.0.6, 14.0.1

**Where did you install Nextcloud from:** nextcloud.com

**Comment by skjnldsv** [comment] 2020-08-19 12:33
Please provide sample pdf

As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-19 12:33 UTC
