### ISSUE TITLE
Can't open PDF when filename or folder name contains a space or special character (' ', é, ...)

### ISSUE THREAD

**Issue by maxrekorder** [nextcloud/files_pdfviewer#381] opened 2021-05-15 10:19 UTC
### :adhesive_bandage: temporary fix
:information_source: There is a temporary fix that takes replaces the pdfviewers code with that from PR #384. To do this replace
`apps/files_pdfviewer/js/files_pdfviewer-main.js` on your instance with [this file from that PR](https://raw.githubusercontent.com/nextcloud/files_pdfviewer/6d81ffbb65c3758bece144e0aff07b4a0ad20eef/js/files_pdfviewer-main.js). Clear your browser's cache and try to open pdfs.

That should fix the issue. Please leave feedback if that does or doesn't work for you. 

---

### Steps to reproduce
1. Create a New Folder
2. Add a PDF file to to the folder. PDF filename containing a space (e.g. name it "Juergen Klopp.pdf"). 
3. Open PDF file "Juergen Klopp.pdf"
4. It also won't work if the folder contains a space

### Expected behaviour
Open the PDF with PDF viewer

### Actual behaviour
PDF.js Version 2.5.207 (build: 0974d6052)
Nachricht: Missing PDF "https://domain.org/remote.php/dav/files/user/New/Juergen%2520Klopp.pdf".

## Server configuration detail

**Operating system:** Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 8.0.25

**PHP version:** 

8.0.5
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 21.0.2 RC1 - 21.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - apporder: 0.12.0
 - calendar: 2.2.1
 - circles: 0.21.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dav: 1.17.1
 - documentserver_community: 0.1.9
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_external: 1.12.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.2.4
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - notes: 4.0.4
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.0.2
 - passman: 2.3.7
 - password_policy: 1.11.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - theming_customcss: 1.8.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - activity
 - admin_audit
 - bruteforcesettings
 - dashboard
 - encryption
 - mail
 - nextcloud_announcements
 - user_ldap
 - workflow_pdf_converter

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.rekorder.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.2.0",
    "overwrite.cli.url": "http:\/\/cloud.rekorder.org",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "data-fingerprint": "11bd4c43db46260d550ca15af9437513",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by ynjo** [comment] 2021-05-15 20:05
Same issue here

**Comment by skjnldsv** [comment] 2021-05-17 06:15
@beardhatcode, can you reproduce the double encoding?

**Comment by beardhatcode** [comment] 2021-05-18 06:34
Yes, I was able to reproduced it last week

**Comment by stefanroesler** [comment] 2021-05-19 09:53
We also have the problem with version 21.0.2

Tested in Firefox and Chrome, also in the backend nginx or Apache2, unfortunately always the same error. As soon as the file has a space, it does not open it. It works fine without spaces.

**Comment by ib-mlatin** [comment] 2021-05-20 17:26
I'm having this same issue with version 21.0.2. It was working perfectly in 21.0.1. Using SMB shares, but it also fails with the "test" files that Nextcloud makes for new users. See images below:

![chrome_2021-05-20_12-23-28](https://user-images.githubusercontent.com/60354324/119022760-9276e400-b966-11eb-8fa2-6435fff193b0.png)

![chrome_2021-05-20_12-25-05](https://user-images.githubusercontent.com/60354324/119022769-960a6b00-b966-11eb-8987-34dedadb94b8.png)

**Comment by obrb** [comment] 2021-05-20 17:28
Actually anything that generates a % in the URL. Umlauts, #, ?, spaces etc... causes this error. A file named "#PDF mit Abständen und Umlauten.pdf produces the following error message:

Message: Missing PDF "https://testcloud.nosarcun.net/remote.php/dav/files/benno/%2523PDF%2520mit%2520Abst%25C3%25A4nden%2520und%2520Umlauten.pdf".

This also happens if a parent folder name contains any of these characters or spacing.

**Comment by Zniets** [comment] 2021-05-20 17:57
Did you all use php8?

**Comment by ib-mlatin** [comment] 2021-05-20 18:30
> Did you all use php8?

No, I'm using the below PHP version:
```
PHP 7.4.18 (cli) (built: May  3 2021 11:27:06) ( NTS )
```

**Comment by szaimen** [comment] 2021-05-20 19:28
I have the same issue now with NC20.0.10 and NC21.0.2

**Comment by xpfgsyb** [comment] 2021-05-20 19:34
> Did you all use php8?

No, NC 21.0.2 with the following PHP version here:
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )

**Comment by fenvarien** [comment] 2021-05-20 20:01
Here we have the same issue with NC 21.0.2 (PHP 7.4.18). To help the students of my school tomorrow, I switched to OnlyOffice as the default PDF viewer as a workaround. But I wonder how this bug could slip through with the release of 21.0.2.
Is it possible to revert to an older version of pdfviewer?

**Comment by szaimen** [comment] 2021-05-20 20:13
cc @nextcloud/server-triage

**Comment by JazMTaz** [comment] 2021-05-21 01:43
Same issue here

Nextcloud 20.0.10

Operating System: | Linux 5.4.0-1035-raspi aarch64
Memory: | 7.63 GB

Nginx version: nginx/1.18.0 (Ubuntu)

Database
Type: mysql
Version: 10.3.29

PHP
Version: 7.4.3

**Comment by pierreGLV9** [comment] 2021-05-21 05:24
PHP 7.4.9
MariaDB 10.3.24
Nexcloud 21.0.1 : Everythink perfectly worked 
Nextcloud 21.0.2 : I encountered the same issue with PDF files, unable to view the files with spaces in name...

**Comment by chrissi55** [comment] 2021-05-21 05:49
Same here with PHP 7.4.18 -> NC 21.0.2

Obviously it is not nexcessary that the PDF Filename contains Spaces - one space in the whole path is causing the error

So not just ../My Name.PDF but also /this.is/my path/to.the.file/My-Name.PDF causes the error

**Comment by beardhatcode** [comment] 2021-05-21 08:07
@skjnldsv , I think it will likely suffice to remove the encode here:

https://github.com/nextcloud/files_pdfviewer/blob/487c93f06b459d26f6eb09353eaa4ba1e05cf50b/src/views/PDFView.vue#L61

The davpath that is returned by viewer is now already "safe" so there is no need to encode it again.

**Comment by Zniets** [comment] 2021-05-21 09:01
How can I test this?

**Comment by beardhatcode** [comment] 2021-05-21 09:08
@Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.

Alternatively, I ou don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change 

```js
!==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
```

to

```js
!==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
```

If you try this out, could you report back if that solved the issue? Thanks :slightly_smiling_face:

**Comment by DmDS** [comment] 2021-05-21 09:14
> Alternatively, I ou don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change....

it helped, thanks!

**Comment by beardhatcode** [comment] 2021-05-21 09:28
@DmDS, do you mean that the proposed edit resolved the issue completely?

**Comment by DmDS** [comment] 2021-05-21 09:33
> 
> 
> @DmDS, do you mean that the proposed edit resolved the issue completely?

yes)

**Comment by Zniets** [comment] 2021-05-21 09:35
> @Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.
> 
> Alternatively, I you don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change
> 
> ```js
> !==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> to
> 
> ```js
> !==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> If you try this out, could you report back if that solved the issue? Thanks 🙂

This worked for me

**Comment by beardhatcode** [comment] 2021-05-21 09:59
Thanks for testing this out @DmDS  and @Zniets :+1:

**Comment by mvvvmd** [comment] 2021-05-21 10:05
I can confirm it works again with the change, after clearing the browser cache.

**Comment by janvier-ninja** [comment] 2021-05-21 10:53
@beardhatcode confirmed it fixed the problem. thanks a lot. :)

**Comment by Mith-09** [comment] 2021-05-21 14:44
It works for as well. Thx a lot @beardhatcode

**Comment by thomasgg23** [comment] 2021-05-21 15:31
Works for me too and saved my weekend thanks @beardhatcode

**Comment by JazMTaz** [comment] 2021-05-21 15:33
Works for me also, thank you

**Comment by jacotec** [comment] 2021-05-21 17:04
@beardhatcode You saved my day!!!

Had this issue on three NC instances, your hotfix solved it! It's unbelievable that this went through release testing :-(

**Comment by Beltran1337** [comment] 2021-05-21 17:54
> @Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.
> 
> Alternatively, I you don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change
> 
> ```js
> !==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> to
> 
> ```js
> !==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> If you try this out, could you report back if that solved the issue? Thanks 🙂

Thank you so much mate!!

Congratz <3

**Comment by Jojo-Burger** [comment] 2021-05-22 07:03
> > @Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.
> > Alternatively, I you don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change
> > ```js
> > !==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```js
> > !==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you try this out, could you report back if that solved the issue? Thanks 🙂
> 
> This worked for me

This did not correct the problem for me...

**Comment by ckrumov** [comment] 2021-05-22 09:00
> > > @Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.
> > > Alternatively, I you don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change
> > > ```js
> > > !==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to
> > > ```js
> > > !==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If you try this out, could you report back if that solved the issue? Thanks 🙂
> > 
> > 
> > This worked for me
> 
> This did not correct the problem for me...

This works for me too!
Did you clear cashe in browser?

**Comment by Jojo-Burger** [comment] 2021-05-22 09:23
> > > > @Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.
> > > > Alternatively, I you don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change
> > > > ```js
> > > > !==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > to
> > > > ```js
> > > > !==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > If you try this out, could you report back if that solved the issue? Thanks 🙂
> > > 
> > > 
> > > This worked for me
> > 
> > 
> > This did not correct the problem for me...
> 
> This works for me too!
> Did you clear cashe in browser?

Yes

**Comment by beardhatcode** [comment] 2021-05-22 09:26
@Jojo-Burger could you share the full path to this file on your instance? (and if possible even the PDF itself)

**Comment by Jojo-Burger** [comment] 2021-05-22 09:27
Logs: [https://s.jordand.fr/yeuqfiOLp9.gif](https://s.jordand.fr/yeuqfiOLp9.gif)

**Comment by Jojo-Burger** [comment] 2021-05-22 09:29
> @Jojo-Burger could you share the full path to this file on your instance? (and if possible even the PDF itself)

Do you want me to share the file with you?

**Comment by beardhatcode** [comment] 2021-05-22 09:35
Yes, If possible, plus the name of the folder this file is in.

Could you try to dowload the file trough the viewer? 
1. click on the pdf
2. The (for you broken) viewer comes up
3. There are three dots in the header `···`, click it
4. A menu pops up with an option to ":arrow_down: download", click that

If that download works, viewer was able to get the file and the problem is caused by this app, if not the problem is with something else.

**Comment by Jojo-Burger** [comment] 2021-05-22 09:39
Indeed I was able to download the file
I uploaded a new PDF and now I can read it

**Comment by Jojo-Burger** [comment] 2021-05-22 09:41
https://cloud.jordand.fr/s/zGnqkrjwqSq9giK
Password #F5rY3DAkJRTf^Tg (The new file)

**Comment by beardhatcode** [comment] 2021-05-22 09:43
@Jojo-Burger I deleted your comment with the pasword, but I have it here

**Comment by beardhatcode** [comment] 2021-05-22 09:44
So the your problem is resolved, @Jojo-Burger?

**Comment by beardhatcode** [comment] 2021-05-22 09:45
Could you give me the path to the file that does not work, something like:

```
Document/My data/personal.pdf
```

Something like that piece of text

**Comment by Jojo-Burger** [comment] 2021-05-22 09:52
/home/raid/cloud/Jordan/files/

I'will test for the files

**Comment by Jojo-Burger** [comment] 2021-05-22 09:55
> Could you give me the path to the file that does not work, something like:
> 
> ```
> Document/My data/personal.pdf
> ```
> 
> Something like that piece of text. I just need the path.
> 
> Could you also try to replace `apps/files_pdfviewer/js/files_pdfviewer-main.js` on your instance with this file: https://raw.githubusercontent.com/nextcloud/files_pdfviewer/6d81ffbb65c3758bece144e0aff07b4a0ad20eef/js/files_pdfviewer-main.js

I tried to file it but it didn't anything

**Comment by beardhatcode** [comment] 2021-05-22 09:58
And what is the name of your file? Does it contain any special characters?

**Comment by Jojo-Burger** [comment] 2021-05-22 09:59
> And what is the name of your file, @Jojo-Burger? Does it contain any special characters?

Yes spaces or dashes

**Comment by beardhatcode** [comment] 2021-05-22 10:00
Can you give a screenshot @Jojo-Burger ?

**Comment by Jojo-Burger** [comment] 2021-05-22 10:01
> Can you give a screenshot @Jojo-Burger ?

[https://s.jordand.fr/XshdfICvsX.png](url) for exemple

**Comment by beardhatcode** [comment] 2021-05-22 10:10
I created a file called `Dossier Pré-Inscription.pdf` on my instance and it was able to open it:
![image](https://user-images.githubusercontent.com/662538/119222842-9df91500-baf6-11eb-80c3-68bb0c5e5abf.png)

How does clicking on that file look for you?

**Comment by jacek-kubek** [comment] 2021-05-22 10:11
I have made change in `apps/files_pdfviewer/js/files_pdfviewer-main.js`  
from:  
```
!==i[a]&&(c+="/"+encodeURIComponent(i[a]));
```
to:  
```
!==i[a]&&(c+="/"+i[a]);
```
At the first look, it has not resolved the problem in my browser (firefox), but:
1. I have checked that it works in another, rare used, browser (ugoogled-chromium).
2. I have cleared cache, cookies and site data in my browser.
3. I have reconnected to Nextcloud.

Now it works like it used to work before upgrading to 21.0.2.

**Conclusion:**
PDF viewer is compatible with 21.0.1 and earlier, but not with the newest 21.0.2.

**Comment by Jojo-Burger** [comment] 2021-05-22 11:12
So until the next update reading PDFs is impossible ....

**Comment by StefanZGit** [comment] 2021-05-22 11:16
We're experiencing the same problem in version 20.0.10.
We've disabled the pdf-viewer app, but downloading the pdfs to read it, is kinda a downgrade...

**Comment by Jojo-Burger** [comment] 2021-05-22 11:27
> We're experiencing the same problem in version 20.0.10.
> We've disabled the pdf-viewer app, but downloading the pdfs to read it, is kinda a downgrade...

yes :/

**Comment by coding4me2** [comment] 2021-05-22 11:29
Thanks now working for me on 21.0.2. I applied the fix but initially it gave me the same issue. As I use docker compose I just issued docker-compose up -d and that reloaded everything. Refreshed the browser page again and it's now showing the pdf files again with spaces in it.

**Comment by Jojo-Burger** [comment] 2021-05-22 11:30
Personally I don't use docker so it's more complicated x)

**Comment by coding4me2** [comment] 2021-05-22 11:35
Did you restart the webserver that nextcloud is on? If not I'd give it a shot.

**Comment by Jojo-Burger** [comment] 2021-05-22 11:37
> Did you restart the webserver that nextcloud is on? If not I'd give it a shot.

No I didn't restart it

**Comment by beardhatcode** [comment] 2021-05-22 12:33
@StefanZGit , the problem is already fixed by PR #384 , and you can replace `apps/files_pdfviewer/js/files_pdfviewer-main.js` on your instance with [this file from that PR](https://raw.githubusercontent.com/nextcloud/files_pdfviewer/6d81ffbb65c3758bece144e0aff07b4a0ad20eef/js/files_pdfviewer-main.js). That fixes the issue. 

The PR still needs to be reviewed. 

@jacek-kubek  The problem is caused by changes in the viewer app that now allow you to open pictures that contain weird characters. But that change caused an error in the PDF viewer which was also fixing files with weird characters, this double fixing of URLs breaks the pdf viewer. PDF viewer will soon be compatible with the latest Nextcloud again.

**Comment by beardhatcode** [comment] 2021-05-22 12:40
@StefanZGit , the change to the viewer app was also ported to version 20 of Nextcloud, I will also make a PR to fix it there

**Comment by Oriann** [comment] 2021-05-22 17:54
Hotfix is not working for me, dunno why.

**Comment by szaimen** [comment] 2021-05-22 17:58
> Hotfix is not working for me, dunno why.

Did you clear the browser cache after applying the fix?

**Comment by Oriann** [comment] 2021-05-22 18:30
Yes I did. I also already tried another browser.

**Comment by beardhatcode** [comment] 2021-05-22 18:41
@Oriann could you give me the filename you are using? Then I can reproduce that. (If possible, if you have a file that breaks the viewer and does not contain any personal data, could you share it here trough github?)

What hotfix did you apply exactly? Did you replace the file or did you do the small edit to that file.

**Comment by Oriann** [comment] 2021-05-22 18:47
@beardhatcode sure !

Here is the error from PDF viewer: 

`PDF.js v2.5.207 (sestavení: 0974d6052)
Zpráva: Missing PDF "https://cloud.********.cz/remote.php/dav/files/stritecky/projekce/BBB-NORMY/hlavn%25C3%25AD%2520pospojov%25C3%25A1n%25C3%25AD-pr%25C5%25AF%25C5%2599ezy.pdf".`

Here is the file:
[hlavní pospojování-průřezy.pdf](https://github.com/nextcloud/files_pdfviewer/files/6526966/hlavni.pospojovani-prurezy.pdf)

**Comment by beardhatcode** [comment] 2021-05-22 19:05
Hmmm @Oriann , that file, with that name works for me in NC21.02. 
![animation](https://user-images.githubusercontent.com/662538/119238063-8fcfe680-bb40-11eb-9bc7-59ca4f32afdd.gif)

Could you try replacing the file like  [this comment](https://github.com/nextcloud/files_pdfviewer/issues/381#issuecomment-846401992) suggests?

You said "file is saved on external storage" do you mean that Nextcloud runs on an external storage server or if this file is included form another federated nextcloud?

**Comment by Oriann** [comment] 2021-05-22 19:12
@beardhatcode I have replaced the file rebooted container again and cleared chrome cache, still it shows it cannot find the pdf file.
I have also uploaded file to root folder of nextcloud to exclude external storage from problem and its not working too...

To external storage, I have 2 servers at home one is for files one is for apps, so I have external storage mounted via NTFS to nextcloud container

**Comment by beardhatcode** [comment] 2021-05-22 19:25
@Oriann could you open the network tab and look at what the precise request is to the pdf-previewer?
It should look something like: 

```
https://cloud.********.cz/apps/files_pdfviewer/?file=https://cloud.********.cz/remote.php/dav/files/root/fwefw%202020_opgave%20%F0%9F%AA%93%20NL%20.pdf/2020_opgave%20%F0%9F%AA%93%20NL%20.pdf
```

**Comment by Jojo-Burger** [comment] 2021-05-23 07:10
https://cloud.*****/remote.php/dav/files/***/Joj/Infra/Licn%2520WHMCS/Order%2520Con.pdf".
for me

**Comment by beardhatcode** [comment] 2021-05-23 07:58
@Jojo-Burger , I'm looking for a request that contains `/apps/files_pdfviewer/?file=`

**Comment by Jojo-Burger** [comment] 2021-05-23 08:12
> @Jojo-Burger , I'm looking for a request that contains `/apps/files_pdfviewer/?file=`

ah I didn't find it personally

**Comment by beardhatcode** [comment] 2021-05-23 08:41
@Jojo-Burger can you give a screenshot/video of a file failing to open? So that I can see what is going on.

**Comment by Jojo-Burger** [comment] 2021-05-23 08:49
> @Jojo-Burger can you give a screenshot/video of a file failing to open? So that I can see what is going on.

https://s.jordand.fr/XUDauUn51h.gif

**Comment by beardhatcode** [comment] 2021-05-23 08:58
Thanks @Jojo-Burger , may I ask you to make another screen capture with the network tab open (be sure to click "disable cache", followed by a refresh, to ensure that all requests are shown)

**Comment by Jojo-Burger** [comment] 2021-05-23 09:03
> Thanks @Jojo-Burger , may I ask you to make another screen capture with the network tab open (be sure to click "disable cache", followed by a refresh, to ensure that all requests are shown)

I don't know how but unchecking and rechecking the "Disable Cache" icon solved my problem.
Thank you very much!

**Comment by beardhatcode** [comment] 2021-05-23 09:15
Ah, @Jojo-Burger, that means your browsers cache was not completely cleared for some reason, ticking that box cleared it. I'm happy to hear it works for you now @Jojo-Burger. :slightly_smiling_face:

**Comment by Oriann** [comment] 2021-05-23 09:30
@beardhatcode here is screenshot
![image](https://user-images.githubusercontent.com/11374526/119255133-491ed280-bbba-11eb-8154-9c787b1371f8.png)

**Comment by beardhatcode** [comment] 2021-05-23 09:49
Hmmm, thats interesting @Oriann , could you test if you are able to download the file through the viewer (that is by clicking download like in the image below)

![image](https://user-images.githubusercontent.com/662538/119255532-ac116900-bbbc-11eb-8ad3-4fd15e19b9a5.png)

If that does not work, could you right-click the download button and choose "copy link location" and share it here?

**Comment by Oriann** [comment] 2021-05-23 09:58
@beardhatcode Yes I am able to download via pdf viewer as you instructed. Also the filename is alright when I am downloading it.
![Animation](https://user-images.githubusercontent.com/11374526/119255864-3c03e280-bbbe-11eb-92aa-1ae7da7adbeb.gif)

**Comment by Oriann** [comment] 2021-05-23 09:59
Here is the link: [https://cloud.ostritecky.cz/s/w3kEqP45NH4RZnA](url)

**Comment by beardhatcode** [comment] 2021-05-23 10:01
Euh @Oriann:
![image](https://user-images.githubusercontent.com/662538/119255939-88e7b900-bbbe-11eb-8a89-4807742c1618.png)

**Comment by Oriann** [comment] 2021-05-23 10:02
@beardhatcode Wow....so thats crazy...

Do you have any idea where is the problem ? Why is shared file accesible to PDF viewer?

**Comment by beardhatcode** [comment] 2021-05-23 10:35
The reason is that shared files have another url. 

I'll first check if I can add that file you just shared via federation to my nextcloud instance. I think that will break as wel

**Comment by beardhatcode** [comment] 2021-05-23 10:39
Hmmm, I federated that file you shared to my server and it works there...

You can create an account invite for me with the email git@beardhatcode.be , I'll see if I can reproduce the error.

**Comment by Oriann** [comment] 2021-05-23 11:55
@beardhatcode so I have rolled back my container from backup one week earlier before update and now it works on Nextcloud ver. 21.0.1, I have tried to update again to 21.0.2 and replace the files as suggested but no luck for me as on desktop devices I am not able to open PDFs and on mobile devices it works normally. I am not that big debugging expert so I will now stay on previous version and wait till next update will be released.

**Comment by MEitelwein** [comment] 2021-05-23 12:48
> @Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.
> 
> Alternatively, I you don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change
> 
> ```js
> !==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> to
> 
> ```js
> !==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> If you try this out, could you report back if that solved the issue? Thanks slightly_smiling_face

This fixed it for me

**Comment by beardhatcode** [comment] 2021-05-23 13:21
@MEitelwein, If possible could you also test if replacing
`apps/files_pdfviewer/js/files_pdfviewer-main.js` on your instance with [this file from the PR that should fix the issue](https://raw.githubusercontent.com/nextcloud/files_pdfviewer/6d81ffbb65c3758bece144e0aff07b4a0ad20eef/js/files_pdfviewer-main.js) works?

**Comment by ib-mlatin** [comment] 2021-05-23 16:16
> @MEitelwein, If possible could you also test if replacing
> `apps/files_pdfviewer/js/files_pdfviewer-main.js` on your instance with [this file from the PR that should fix the issue](https://raw.githubusercontent.com/nextcloud/files_pdfviewer/6d81ffbb65c3758bece144e0aff07b4a0ad20eef/js/files_pdfviewer-main.js) works?

The file from the PR fixes the issue for me.

**Comment by MEitelwein** [comment] 2021-05-23 18:15
> @MEitelwein, If possible could you also test if replacing
> `apps/files_pdfviewer/js/files_pdfviewer-main.js` on your instance with [this file from the PR that should fix the issue](https://raw.githubusercontent.com/nextcloud/files_pdfviewer/6d81ffbb65c3758bece144e0aff07b4a0ad20eef/js/files_pdfviewer-main.js) works?

Yes, the file from the PR fixes it for me

**Comment by danielepercivaldi** [comment] 2021-05-23 19:40
Thanks @MEitelwein , that works for me.

**Comment by StefanZGit** [comment] 2021-05-23 20:51
> @StefanZGit , the change to the viewer app was also ported to version 20 of Nextcloud, I will also make a PR to fix it there

Thank you. We've changed the js and it's now working again for us.

**Comment by sinichi19** [comment] 2021-05-24 04:46
> @Zniets, you could edit that file and change the aforementioned line to `encodedDavPath += pathSections[i]` and compile the new js. And see if this works.
> 
> Alternatively, I you don't want to compile, you could edit `apps/files_pdfviewer/js/files_pdfviewer-main.js` and change
> 
> ```js
> !==i[a]&&(c+="/"+encodeURIComponent(i[a]));return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> to
> 
> ```js
> !==i[a]&&(c+="/"+i[a]);return t&&(c=i[0]+"//"+i[2]+c),c}}
> ```
> 
> If you try this out, could you report back if that solved the issue? Thanks 🙂


confirmed fixed, 

after update to 20.0.10 cant open pdf, but after i tried this is now working .


Thank You Sir

**Comment by maxrekorder** [comment] 2021-05-24 09:14
Thank you so much for the help. The bugfix works!

In the future it would be nice if the functions of the app were tested before a new update is rolled out.

**Comment by beardhatcode** [comment] 2021-05-24 09:33
The fix for this issue is not yet merged, to help others find this out I'll reopen the issue

**Comment by rogercreagh** [comment] 2021-05-24 16:45
Any idea of timescale when this will be available as a release for NC20.x (currently on v2.0.1) that can be installed as an update from within NC for those of us who don't have sudo access to the server? Its a right pain at present - we've had to switch pdf viewing to OpenOffice and it is so slooow. (we have loads of pdf files and folder names with spaces and all was good till we updated to NC20.x this week)

**Comment by aleskomarek** [comment] 2021-05-25 05:22
This fix repair opening my own PDF files, but does not solve opening shared PDF files.

**Comment by beardhatcode** [comment] 2021-05-25 05:47
@aleskomarek did you replace the entire file or just the did you just do the mini edit?

**Comment by aleskomarek** [comment] 2021-05-25 06:19
> 
> 
> @aleskomarek did you replace the entire file or just the did you just do the mini edit?

without file replacement or file edition

**Comment by Oriann** [comment] 2021-05-25 06:37
@aleskomarek wait you said that without any fix you have working pdf viewer from cloud but not from shared link?

**Comment by aleskomarek** [comment] 2021-05-25 06:43
> 
> 
> @aleskomarek wait you said that without any fix you have working pdf viewer from cloud but not from shared link?

sorry for my inaccuracy, i uploaded PDF file to my account and with this fix I opened this file in buildin PDF viewer, but when I shared this file to another user and this user opens this shared file in buildin PDF viewer problem persists - file is missing

**Comment by beardhatcode** [comment] 2021-05-25 06:52
@aleskomarek , could you ask that other user to clear their browser cache? They are likely still using the old code.

**Comment by aleskomarek** [comment] 2021-05-25 06:54
> 
> 
> > @aleskomarek wait you said that without any fix you have working pdf viewer from cloud but not from shared link?
> 
> sorry for my inaccuracy, i uploaded PDF file to my account and with this fix I opened this file in buildin PDF viewer, but when I shared this file to another user and this user opens this shared file in buildin PDF viewer problem persists - file is missing

I'm have shared folder to another user and I moved a PDF file to this shared folder. Another user has problem with opening this PDF file in buildin PDF viewer. In NC version 21.0.1 this was ok.

**Comment by aleskomarek** [comment] 2021-05-25 07:19
> 
> 
> @aleskomarek , could you ask that other user to clear their browser cache? They are likely still using the old code.

You are right. Now this is also functional over shared folder/file. Trouble was really in user's web browser. After restart browser and clear cache this is ok. I apologize for my fault.

**Closed** 2021-05-25 14:35 UTC
Labels: bug

**Comment by RodSeq** [comment] 2021-05-27 07:07
I confirm I had the same issue after upgrading my instance to NC 21.0.2, now solved with your temporary fix replacing the file "apps/files_pdfviewer/js/files_pdfviewer-main.js" + restarting my browser. Many thanks for your temporary fix for that very critical issue !

Before that a new NC stable version including your fix is released, I suggest that Nextcloud removes 21.0.2 from the "stable" release channel, avoiding that other NC Users experience that critical bug.

**Comment by Oriann** [comment] 2021-05-27 07:19
@RodSeq totally agree, some users might not be able to fix that easily because lack of experience. Some users may not be even able to access this file location cos of hosting limits.

**Comment by acsfer** [comment] 2021-05-27 08:39
Please note that "stable" doesn't mean "bug free".
CI tests doesn't cover ALL possible scenarios, in any software.

Last but not least, "stable" also doesn't mean "apply it blindly". 😉 
Even more on critical (enterprise) environments.
