### ISSUE TITLE
feature request : Hypothes.is integration to pdf.js viewer 

### ISSUE THREAD

**Issue by bijang** [nextcloud/files_pdfviewer#117] opened 2019-01-06 11:48 UTC
With focus on collaboration and now moodle integration, it would be really forward thinking to bring this as an add on to the nextcloud platform pdf.js viewer. It is based on an open standard and increasingly used in academic journals

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by skjnldsv** [comment] 2019-04-30 08:50
Duplicate of #129

**Closed by skjnldsv** 2019-04-30 08:50 UTC
