### ISSUE TITLE
PDF Viewer Release 29.0.9 miss some source file

### ISSUE THREAD

**Issue by l-marquet** [nextcloud/files_pdfviewer#1087] opened 2024-11-28 14:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

PDF Viewer Release [v29.0.9](https://github.com/nextcloud/files_pdfviewer/releases/tag/v29.0.9) is bugged, in the JS directory it miss all the JS files.
So in NextCloud 29.0.9 PDF Viewer is not working

### Steps to reproduce
1. Open the ZIP or TAR.GZ archive and look at the JS folder

### Expected behaviour
Find the following files :
```
files_pdfviewer-data_image_svg_xml_....js
files_pdfviewer-main.js
files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-xxxxxx_mjs.js
files_pdfviewer-public.js
files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-xxxxxx_mjs.js
files_pdfviewer-workersrc.js
```

### Actual behaviour
No one file

### Server configuration

**Web server:** Apache

**Database:** PostgreSQL

**Nextcloud version:** 29.0.9

**Comment by Antreesy** [comment] 2024-12-09 12:24
Duplicate of #1080, please refer to discussion / temporary solution there

**Closed by Antreesy** 2024-12-09 12:24 UTC
Labels: bug, 0. Needs triage
