### ISSUE TITLE
PDF print preview is empty

### ISSUE THREAD

**Issue by MaxGitHubAccount** [nextcloud/files_pdfviewer#301] opened 2021-02-01 17:28 UTC
### Steps to reproduce
1. Open a pdf file in nextcloud (which has one page)
2. click the print icon on the upper right

### Expected behaviour
A one page preview before printing is shown

### Actual behaviour
A preview of two white pages is shown

At least: When printed - the page is correctly printed

### Server configuration

**Operating system**:
Debian Buster 4.19.0-12-amd64

**Web server:**
Apache/2.4.38 (Debian)

**Database:**
MariaDB Ver 15.1 Distrib 10.3.27-MariaDB

**PHP version:**
7.3.19-1

**Nextcloud version:** (see Nextcloud admin page)
20.0.6.1

**Where did you install Nextcloud from:**
package downloaded from website using the documentation

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - documentserver_community: 0.1.8
  - event_update_notification: 1.2.0
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - passwords: 2020.12.2
  - photos: 1.2.3
  - polls: 1.6.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.5
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_pdf_converter: 1.5.1
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - richdocuments
  - riotchat
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "**REMOVED SENSITIVE VALUE**"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.6.1",
        "overwrite.cli.url": "**REMOVED SENSITIVE VALUE**",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

### Client configuration
**Browser:**
84.0.2 (64-Bit) Linux - happens also in Windows

**Operating system:**
Linux / Windows

#### Browser log

Uncaught TypeError: e.classList is undefined
    hasNodeOrAnyParentClass excludeClickOutsideClasses.js:22
    clickOutsideMiddleware excludeClickOutsideClasses.js:22
    r v-click-outside.umd.js:1
    handler v-click-outside.umd.js:1
    setTimeout handler*handler/< v-click-outside.umd.js:1
    handler v-click-outside.umd.js:1
excludeClickOutsideClasses.js:22:425
    hasNodeOrAnyParentClass excludeClickOutsideClasses.js:22
    hasNodeOrAnyParentClass self-hosted:1161
    clickOutsideMiddleware excludeClickOutsideClasses.js:22
    clickOutsideMiddleware self-hosted:1161
    r v-click-outside.umd.js:1
    handler v-click-outside.umd.js:1
    (Async: setTimeout handler)
    handler v-click-outside.umd.js:1
    handler v-click-outside.umd.js:1
#print_progress_percent is undefined. 2 l10n.js:825:6

​

**Comment by skjnldsv** [comment] 2021-02-23 10:02
I can't reproduce the issue.
Can you do a screencast? Does it happens with all pdfs? Or only some?

**Comment by MaxGitHubAccount** [comment] 2021-03-01 13:28
Hi @skjnldsv
Thanks for getting back. How can I share a screencast with you? If you provide me an e-mail(via pm?) I could share a video with you and prepare some examples.

**Comment by miguelarios** [comment] 2021-07-08 19:04
> I can't reproduce the issue.
> Can you do a screencast? Does it happens with all pdfs? Or only some?

I can chime in here a way to reproduce this is opening a pdf inside a shared directory. I am seeing this error.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/24581058/124976832-5cb0bc00-dff5-11eb-8ae2-d69dd4abfda5.png">


```
Uncaught (in promise) Error: Missing PDF file.
    _callee7$/</< https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:1107
    promise callback*_callee7$/< https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:1102
    promise callback*_callee7$ https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:1082
    tryCatch https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:3038
    invoke https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:3214
    method https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:3081
    asyncGeneratorStep https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:338
    _next https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:340
    _asyncToGenerator https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:340
    _asyncToGenerator https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:340
    open https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:1117
    webViewerOpenFileViaURL https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:2197
    webViewerInitialized https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:2171
    promise callback*run https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:804
    webViewerLoad https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:261
    EventListener.handleEvent* https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:267
    __webpack_require__ https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:42
    <anonymous> https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:106
    <anonymous> https://cloud.miguelarios.com/apps/files_pdfviewer/js/pdfjs/web/viewer.js?v=2.0.1:109
```

**Comment by szaimen** [comment] 2023-06-23 09:01
Hi,  there have been multiple updates to the pdfviewer in the meantime. Can you please update e.g. to Nextcloud 26.0.3 and check if one of it fixed the problem for you? Thank you!

**Comment by joshtrichards** [comment] 2024-05-05 14:05
Closing due to age and lack of follow-up confirmation after 3 years. :)

If still occurring feel free to let us know.

**Closed by joshtrichards** 2024-05-05 14:05 UTC
Labels: bug, needs info, 0. Needs triage
