### ISSUE TITLE
Double-click on PDF results in two stacked PDF Viewer instances, one of them can't be closed

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/files_pdfviewer#514] opened 2021-10-19 11:09 UTC
### Steps to reproduce
1. Open Files App
2. Find a PDF
3. *Double*-click it
4. You will see the PDF in the Viewer
5. Click on the "Close"-X top right
6. In most cases the PDF closes and leaves you with an empty instance of the reader you can't close anymore.

### Expected behaviour
PDF should be opened once only or both viewer instances should have a working "Close"-X. I know that in this case a single click would be appropriate. Although its 2021, lots of people don't know when they should double-click and when they shouldn't. 

### Actual behaviour
I guess that the first click starts opening the viewer, the second click seems to interrupt this and opens another instance of the viewer where you can read the PDF. When you close this one, the first instance remains and since it was not loaded completely the "Close"-X does not work.

**Nextcloud version:** (see Nextcloud admin page)
Verified in NC 21 and 22

**Comment by szaimen** [comment] 2021-11-10 13:54
Duplicate of https://github.com/nextcloud/viewer/issues/893

**Closed by szaimen** 2021-11-10 13:54 UTC
