### ISSUE TITLE
Cannot open PDF inside shared folders

### ISSUE THREAD

**Issue by hmt** [nextcloud/files_pdfviewer#305] opened 2021-02-05 10:48 UTC
**Describe the bug**
A publicly shared PDF **inside a folder** cannot be opened in the viewer. It says `Invalid or corrupted PDF file`

**To Reproduce**
1. Create folder and add PDF file to it
2. Share folder and create public link
3. Open public link
4. Click on PDF file to view

**Expected behavior**
File can be viewed

**Screenshots**
<img width="361" alt="image" src="https://user-images.githubusercontent.com/1246495/107015052-a96d3e00-679c-11eb-9a92-a72756577c36.png">
File cannot be viewed

** Platform **
everywhere

**Browser log**
```
Uncaught (in promise) Error: Invalid or corrupted PDF file.
    _callee7$/</< app.js:817
    promise callback*_callee7$/< app.js:815
    promise callback*_callee7$ app.js:776
    Babel 8
        tryCatch
        invoke
        method
        asyncGeneratorStep
        _next
        _asyncToGenerator
        _asyncToGenerator
        open
    webViewerOpenFileViaURL app.js:1947
    webViewerInitialized app.js:1917
    promise callback*run app.js:478
    webViewerLoad viewer.js:218
    EventListener.handleEvent* viewer.js:228
    Webpack 3
        __webpack_require__
        <anonymous>
        <anonymous>
app.js:817:16

```

**Additional context**
It is fine to share a single PDF. A single PDF can be opened just fine. This only happens for PDF files that are in a shared folder.
This happened immediately after the 20.0.7 update.
First posted here: https://github.com/nextcloud/viewer/issues/764

**Comment by RealKelsar** [comment] 2021-02-05 11:28
Hi,

same Problem here, but I notice it tries a Auth Call to our SAML Provider, but that one gets suppresed by the browser because of CSP.

Opening the same PDF in OnlyOffice from the context Menu does work finde and I do not see such a call there.

**Comment by RealKelsar** [comment] 2021-02-05 11:31
Guess it is the same Issue as in #286

**Comment by hmt** [comment] 2021-02-05 11:40
Yes, you're correct. Didn't see that bug. But for me this only appeared in 20.0.7

**Comment by RealKelsar** [comment] 2021-02-05 11:48
Same here.

**Comment by Hanskes** [comment] 2021-02-05 13:28
Same problem here, since update to 20.0.7

**Comment by szaimen** [comment] 2021-02-07 00:40
cc @skjnldsv

**Comment by ksteinb** [comment] 2021-02-08 10:31
Same here

**Comment by Mehvix** [comment] 2021-02-08 15:48
Same here.

**Comment by dsiminiuk** [comment] 2021-02-08 19:41
+1

**Comment by nderambure** [comment] 2021-02-08 23:15
This is the same bug than here : https://github.com/nextcloud/files_pdfviewer/issues/207

**Comment by wankdanker** [comment] 2021-02-09 19:51
The problem is that the URL that is fetched by the PDF viewer appears to be URL encoded like:

`https://cloud.nendzynski.de:8443/index.php/s/o49EBjHoe78GQEj/download%3Fpath%3D/%26files%3DTest.pdf`

Where it should be:

`https://cloud.nendzynski.de:8443/index.php/s/o49EBjHoe78GQEj/download?path=/&files=Test.pdf`

And the server responds with a 302 redirect to the login page.

![image](https://user-images.githubusercontent.com/624233/107419534-ea8b8800-6ae5-11eb-8d9b-c19361f270d6.png)

I am not familiar with the code base, but I'm trying to trace where the URL is generated. Maybe this will help someone else though.

**Comment by LPJon** [comment] 2021-02-10 18:18
Same here. I get this error on Shared PDF Viewing ONLY:

```
PDF.js v2.4.456 (build: 228a591c)
Message: Invalid PDF structure.
```

**Comment by dsiminiuk** [comment] 2021-02-10 18:28
It looks like a fix is in progress in #309

**Comment by skjnldsv** [comment] 2021-02-17 07:31
fix in https://github.com/nextcloud/files_pdfviewer/pull/319

**Closed by skjnldsv** 2021-02-17 07:31 UTC

**Comment by hmt** [comment] 2021-02-19 10:10
Tahnks for fixing this bug. Is it possible to get the app released as an update any time soon? People are shouting at me all the time because they don't understand how to download a pdf.
