### ISSUE TITLE
Incorrect font render

### ISSUE THREAD

**Issue by wntbrian** [nextcloud/files_pdfviewer#89] opened 2018-07-11 01:27 UTC
### Steps to reproduce
1. Open pdf file in PDF viewer 1.2.1

### Expected behaviour
Show correct pdf document

### Actual behaviour
incorrect font render, but in Adobe Acrobat Reader view correct.

![image](https://user-images.githubusercontent.com/31837915/42545252-1748ddea-84fa-11e8-8a51-e68827dda046.png)
![image](https://user-images.githubusercontent.com/31837915/42545494-abcf5470-84fb-11e8-8975-03089dc50b82.png)

### Server configuration
**Operating system**:
`   Static hostname: nextcloud-02
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 29eb81b25dc14c6b8991a49a75213a8c
           Boot ID: c77b7760cf814bf48d51bbf06271894e
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.16.1.el7.x86_64
      Architecture: x86-64`
**Web server:**
`Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 12 2017 21:03:28`
**Database:**
`/usr/libexec/mysqld  Ver 5.5.52-MariaDB for Linux on x86_64 (MariaDB Server)`
**PHP version:**
`PHP 7.0.18 (cli) (built: Apr 11 2017 14:25:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies`
**Nextcloud version:** (see Nextcloud admin page)
`Nextcloud 13.0.4`
**Where did you install Nextcloud from:**
https://nextcloud.com/install/

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```
**Font in document:**
![screenshot-4](https://user-images.githubusercontent.com/31837915/42545834-8f676546-84fd-11e8-9aaa-af85e4d5af36.png)
![screenshot-3](https://user-images.githubusercontent.com/31837915/42545835-8f949bce-84fd-11e8-86c4-100f7e7999b4.png)
![screenshot-2](https://user-images.githubusercontent.com/31837915/42545836-8fc11af0-84fd-11e8-9105-791b335b8f73.png)

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.130.101",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.130.25",
        "dbtype": "mysql",
        "version": "13.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Client configuration
**Browser:**

**Operating system:**
MacOS High Sierra10.13.6 / Windows 10
Chrome / Safari
#### Nextcloud log (data/owncloud.log)
no errors

#### Browser log
```
Summary
URL: https://domain/files_pdfviewer/vendor/pdfjs/web/l10n.js?v=1.2.1
Status: 404
Source: Network
Summary
URL: https://domain/files_pdfviewer/vendor/pdfjs/web/compatibility.js?v=1.2.1
Status: 404
Source: Network
```

**Comment by skjnldsv** [comment] 2020-08-19 12:35
Do you have a sample pdf?

**Comment by wntbrian** [comment] 2020-08-28 13:49
Sorry, don't have access to this project anymore.

**Comment by skjnldsv** [comment] 2020-08-29 07:26
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-29 07:26 UTC
Labels: 0. Needs triage, bug, needs info
